site_name: My Learning Journey
site_description: Documenting my learning and growth
site_author: Phung Dao
site_url: https://phungdx.github.io/my-blog/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Blog:
    - blog/index.md
